name: mint
description: Create minified versions of an existing container images

inputs:
  target:
    description: The target image
    required: true
runs:
  using: composite
  steps:
    - name: Setup mint
      run: |
        mkdir -p /tmp/mint
        cd /tmp/mint
        if [ ! -f /tmp/mint/mint ]; then
          rm -f mint.tar.gz
          # Get the current released tag_name
          VER=$(curl -sL https://api.github.com/repos/mintoolkit/mint/releases \
            | grep tag_name | head -n1 | cut -d'"' -f4)
          curl -L -o mint.tar.gz "https://github.com/mintoolkit/mint/releases/download/${VER}/dist_linux.tar.gz"
          tar -xvf mint.tar.gz --strip-components 1
        fi
        echo "/tmp/mint" >> $GITHUB_PATH
      shell: bash
