name: Continuous Integration Labels
on:
  workflow_run:
    workflows: ['Continuous Integration', 'Continuous Integration Secure']
    types: [requested, completed]

permissions:
  deployments: write
  packages: write
  pull-requests: write
  
env:
  GH_TOKEN: ${{ github.token }}
  PR_NUMBER: ${{ github.event.workflow_run.pull_requests[0] != null && github.event.workflow_run.pull_requests[0].number || '' }}

jobs:
  start:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request'
    steps:
      - name: Context
        run: echo "$CONTEXT"
        env:
          CONTEXT: ${{ toJSON(github) }}
  