name: Continuous Integration Secure
# Secure execution of continuous integration jobs
# which are performed upon completion of the
# "Continuous Integration" workflow
# https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
on:
  workflow_run:
    workflows: ['Continuous Integration']
    types: [completed]

permissions:
  deployments: write
  packages: write
  pull-requests: write
  
jobs:
  codecov:
    runs-on: ubuntu-latest    
    steps:
      - run: echo "${{ toJSON(github) }}"
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(context)