name: Continuous Integration
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  checks: write

env:
  IMAGE_REPO_PREVIEW: ghcr.io/${{ github.repository }}/preview

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$HOME"
      - run: echo "$PWD"
      - run: echo "$PATH"
      - run: ls -la "$HOME/.local/bin"
      - run: env -0 | sort -z | tr '\0' '\n'
      - name: Setup mint
        run: |
          mkdir -p "$HOME/.local/bin"
          cd "$HOME/.local/bin"
  
          # Get the current released tag_name
          VER=$(curl -sL https://api.github.com/repos/mintoolkit/mint/releases \
            | grep tag_name | head -n1 | cut -d'"' -f4)
          curl -L -o mint.tar.gz "https://github.com/mintoolkit/mint/releases/download/${VER}/dist_linux.tar.gz"
          tar -xvf mint.tar.gz --strip-components 1
  
          echo "Installed mint:${VER}"
      - run: mint -v
      - run: echo "${{ toJSON(github) }}"
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(context)
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(JSON.stringify(context))
      - id: major
        env:
          VERSION: "16.1.2"
        run: echo "version=${VERSION%%.*}" >> "$GITHUB_OUTPUT"
      - run: echo "${{ steps.major.outputs.version }}"
  
  build:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
      packages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-mint
      - name: 'Container: Build and preview image'
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
          docker build --tag $IMAGE_REPO_PREVIEW:main-fat .
          mint slim --target $IMAGE_REPO_PREVIEW:main-fat --tag $IMAGE_REPO_PREVIEW:main --preserve-path /usr/share/nginx/html
          docker push $IMAGE_REPO_PREVIEW:main
          docker image list
        env:
          DOCKER_BUILDKIT: 1
