name: Continuous Integration
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  checks: write

env:
  IMAGE_REPO_PREVIEW: ghcr.io/${{ github.repository }}/preview

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJSON(github) }}"
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(context)
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(JSON.stringify(context))
      - id: major
        env:
          VERSION: "16.1.2"
        run: echo "version=${VERSION%%.*}" >> "$GITHUB_OUTPUT"
      - run: echo "${{ steps.major.outputs.version }}"
  
  build:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
      packages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-mint
      - name: 'Container: Build and preview image'
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
          docker build --tag $IMAGE_REPO_PREVIEW:main-fat .
          mint slim --target $IMAGE_REPO_PREVIEW:main-fat --tag $IMAGE_REPO_PREVIEW:main --preserve-path /usr/share/nginx/html
          docker push $IMAGE_REPO_PREVIEW:main
          docker image list
        env:
          DOCKER_BUILDKIT: 1
