name: Test
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test-module: [1, 2]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: yarn
      - run: yarn install --frozen-lockfile --non-interactive
      - run: |
          mkdir -p dist/screenshots/files
          echo "{}" > "dist/screenshots/coverage-final.json"
          echo "{}" > "dist/screenshots/files/text${{ matrix.test-module }}.txt"
        env:
          KEY: ${{ matrix.test-module }}

      - name: Generate artifact key
        id: artifact-key
        run: echo "artifact-key=${TEST_MODULE//\//_}" >> $GITHUB_OUTPUT
        env:
          TEST_MODULE: ${{ matrix.test-module }}
      - name: Store
        uses: actions/upload-artifact@v4
        with:
          name: matrix-coverage-${{ steps.artifact-key.outputs.artifact-key }}
          path: dist/screenshots/
          retention-days: 1

  collect-test-results:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: yarn
      - run: yarn install --frozen-lockfile --non-interactive
      - uses: actions/download-artifact@v4

      - run: |
          mkdir -p dist/screenshots
          for file in matrix-coverage-*/; do
            mv -f "$file" "dist/screenshots/"
          done
          ls -Rla dist/screenshots
